### ISSUE TITLE
Specify appropriate build command filters for Linux 3.14.79, 3.16.65, 4.4.178, 4.9.168, 4.14.111, 4.19.34, 5.0.7

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#105]
Good build command filters are very useful since they allow:
- to reduce a consumption of computational resources for many different operations with build  bases as well as to reduce an occupied space on disks,
- to enable better visualization of collected data in cases when it can be visualized,
- to get rid of annoying failures, e.g. when CIF can not request source code that is out of interest for users.

Nobody forces to use build command filters, so, if you are ready to mee issues like described above you are welcome.

Currently specified filters for the Linux kernel should be fixed since they are incomplete and redundant.

**Comment by 17451k** [comment]
Please submit new filters as a pull request so I can review them before merge.

**Comment by 17451k** [comment]
It seems that this is not relevant anymore. If I am wrong - please reopen the issue.

**Comment by eunovm** [comment]
Everything works, so, nobody cares. Let's be engaged when something will fail.
