### ISSUE TITLE
Disallow refilling build bases with changed configurations

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#106]
Recently I encountered a tricky issue: when I changed the configuration and refill a build base completely there was not configuration changes in `meta.json`. I suggest the simple solution. Do not allow to refill partially or completely existing build bases when configurations are changed.

Of course, the solution is rather primitive, since often configuration changes do not affect results dramatically, but to avoid tricky conflicts it is much easier just to disable them by design.

**Comment by 17451k** [comment]
Command line options (like --force) are also stored in the configuration and are supposed to be changed between two different Clade launches on the same build base (first launch with "force": false and second with "force": true).

Implementation of your solution will hinder the ability to re-launch Clade on the same build base and with different configurations, which is quite useful when you still do not have a fully working configuration and experiment with different options.

I think it should be possible for Clade to automatically check whether configuration change affect already collected part of the build base or not.

Concerning your issue, I think it would be better to simply implement proper way to update configuration inside `meta.json`.

**Comment by eunovm** [comment]
> Command line options (like `--force`) are also stored in the configuration and are supposed to be changed between two different Clade launches on the same build base (first launch with `"force": false` and second with `"force": true`).

You can filter this option out when comparing configurations. Ditto may be for some other auxiliary options like, say, for logging.

> 
> Implementation of your solution will hinder the ability to re-launch Clade on the same build base and with different configurations, which is quite useful when you still do not have a fully working configuration and experiment with different options.

There may be a special development mode that will may to launch with different configurations, but will not provide guaranties that everything will be okay. It will be necessary quite rare, so, it does not bad.

> 
> I think it should be possible for Clade to automatically check whether configuration change affect already collected part of the build base or not.

There may be non-trivial things in particular plugins, so, I expect errors, especially, when for new features corresponding assessments will not be performed in time. But for the development mode this may be expected. Normal users can wait for safe and complete rebuilding of build bases.

**Comment by 17451k** [comment]
Starting with c0eaa57b0317e216da1d0e99ade9a553675097a9 Clade automatically detects whether configuration change affects already collected part of the build base or not.

Commit 9eaf44234a5b3da80876fb9b041722c7c3ed08e9 makes sure that such changes are correctly written to the `meta.json` file
