### ISSUE TITLE
Simple method for sanity check of Clade directory

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#108]
At the moment I check for Clade directory validity manually by the following 2 checks:

- Check that a provided path is an existing directory.
- Check that there is file "meta.json" in it.

I am not sure that there is an appropriate API in Clade itself. Moreover, there can be some extra checks. Maybe Clade can do them during initialization or there can be an explicit interface for this.

**Comment by 17451k** [comment]
Starting from the Clade 3.0.7 (not yet released) you will be able to use the following interface:

```
c = Clade(work_dir="clade-linux3.14")
if not c.is_work_dir_ok():
    raise RuntimeException("Clade working directory does not exist")
```

The same functionality is available through command line:

```
$ clade-check clade-linux3.14
$ 16:24:56 clade: Working directory is OK and contains data from the following extensions:
Storage, LD, CmdGraph, PidGraph, Callgraph, Path, AR, Functions, MV, AS, Info, CC, SrcGraph
```
