### ISSUE TITLE
Do not duplicate references from expansions

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#117]
For instance, for the [given source line](https://elixir.bootlin.com/linux/v3.14.79/source/arch/x86/include/asm/io.h#L93) Clade provides 2 equal sets of references from macro expansions for 2 "different" **readq**. I suggest to always consider just first word matching a name in this case.

**Comment by 17451k** [comment]
Fixed in 10aff6ec9c4f2a17bf6944015e86313bdd961c8c.
