### ISSUE TITLE
Invalid Clade version

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#126]
After uninstalling an old Clade version, manual removing of _lib/python3.6/site-packages/clade_, renaming a Clade GIT repository and installing a new Clade version from PyPI, I get an invalid Clade version from CLI and in _meta.json_:
```
$ clade -v
Clade v2.0-556-g022d76316
```
I suggest that something may be wrong in detecting Clade version.

**Comment by eunovm** [comment]
I would like to add that I installed Clade in a dedicated virtual environment and I did not install Clade in a system ever.

**Comment by 17451k** [comment]
I am unable to reproduce this, but I have noticed that Clade also reports its version incorrectly on Ilja's computer. In his case, its due to the usage of `git pull origin master`, which does not fetch new tags. You should use `git pull` instead.

**Comment by eunovm** [comment]
In new virtual environment there is no such the issue. So, as a workaround for PyPI one can create a new virtual environment.

**Comment by eunovm** [comment]
But for the following requirements [reqs.txt](https://github.com/17451k/clade/files/3661593/reqs.txt) installing Clade in a new virtual environment gives:
```
$ clade -v
Clade v2.0-565-ge5a83a5ab
```

**Comment by eunovm** [comment]
The issue seems to be related with a very old installation. So, do not install Clade many times in different places.

**Comment by eunovm** [comment]
It turned out that scripts took version of a Git repository that contained virtual environment directory.
