### ISSUE TITLE
Optimize memory consumption for Clade queries

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#127]
@IljaZakharov revealed that clade.get_cmd() eats very much memory that means that either raw data or its retrieving in Clade is suboptimal. I suggest to investigate other interfaces intended for obtaining small portions of data from a build base.

**Comment by eunovm** [comment]
Of course, it is better to track the issue with a large enough build base. So, unfortunately, it is hard to include some corresponding checks within the Clade test suite.

**Comment by eunovm** [comment]
PS: here I do not suggest any radical underlying changes. In particular, this is regarding representation of data within JSON files. For me it is okay if simple operations will not require enormous computational resources.

**Comment by eunovm** [comment]
This issue is of the highest priority since I suggest that it can be trivially fixed while implementing workarounds in callers that are not allowed to consume much computational resources is hard and time consuming.

**Comment by 17451k** [comment]
You can reduce memory usage by passing command type (it is a new optional argument) to the `clade.get_cmd()` method (and some others as well). Implemented in `v.3.2.3`.

See https://github.com/17451k/clade/commit/47dee8aabc265bc7dfc7f7f82ec03dfc005124b9 for changes.

**Comment by 17451k** [comment]
More improvements were committed to the master branch. I think the issue can be closed now.
