### ISSUE TITLE
Collecting dependencies on Windows was broken

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#136]
Commit cc0d29f7873c5c3c95f739237e0d8a47147e4ddd changed "deps_cmd" to ["dir"] in clade/extensions/cl.py likely to test some changes without actual launch on Windows.

It does not seem that anybody complains about this issue since that time, so, unlikely there are many users of Clade on Windows. In particular, I would not like to test whether Clade is working on Windows.

**Comment by 17451k** [comment]
702f02c269b5b88d13367e489f800153ce05ffb5 fixes the issue with `["dir"]`, but it is not enough: cl.exe can't find standard libraries and fails with a corresponding error. Maybe path to them is specified using environment variables?

**Comment by eunovm** [comment]
I am not an expert in Windows build processes. Maybe environment variables, maybe command-line options say where to find libraries. Anyway, let's postpone that work until there will be any real users of Clade on Windows.
