### ISSUE TITLE
UnicodeDecodeError when preparing Klever build base for linux-3.14.79

### ISSUE THREAD

**Issue by sim642** [17451k/clade#140]
Following [the Klever tutorial](https://klever.readthedocs.io/en/latest/tutorial.html#preparing-build-bases), [the downloadable prepared build base](https://forge.ispras.ru/attachments/download/7328/build-base-linux-3.14.79-x86_64-allmodconfig.tar.xz) did not work with Klever 3.5.dev72+g0c1e1d864 due to a Clade version mismatch. Therefore I followed the same instructions to generate it on my own.

Unfortunately Clade crashes after the build with:
```
09:01:30 clade: Variables: Parsing global variables initializations
09:01:31 clade: Variables: Finished in 0:00:16
Traceback (most recent call last):
  File "/mnt/klever/klever_src/venv/bin/clade", line 8, in <module>
    sys.exit(main())
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/__main__.py", line 222, in main
    c.parse_list(extensions, args.force_exts)
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/__init__.py", line 247, in parse_list
    ext_obj.parse(self.cmds_file)
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/extensions/abstract.py", line 104, in parse_wrapper
    return parse(self, *args, **kwargs)
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/extensions/variables.py", line 47, in parse
    self.__process_init_global()
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/extensions/variables.py", line 83, in __process_init_global
    self.variables = parse_variables_initializations(
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/extensions/initializations.py", line 378, in parse_variables_initializations
    data = ''.join(list(iter_init_global())) + '\n'
  File "/mnt/klever/klever_src/venv/lib/python3.10/site-packages/clade/extensions/info.py", line 374, in iter_init_global
    yield line.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 12: invalid start byte
```

I copied the `iter_init_global` logic with debug printing to a separate script just to see what input it crashes on, and it happens after
```
declaration: static struct idxdata tbl_middle_hvflip_low[8U]; path: /mnt/klever/build_bases/linux-3.14.79/drivers/media/usb/gspca/gl860/gl860-mi2020.c; type: global
```
where the corresponding kernel source contains the string literal `"\x90\x00\x06"`.
At some point Clade must be unescaping this literal, writing it to an init_global file and later trying to read it back in as UTF-8, but it isn't valid UTF-8.
Arbitrary string literals probably shouldn't be assumed to be UTF-8 decodable to begin with.

Anyway, as the result of this Clade crash, some part of the build base seems to be missing because when used with Klever, other missing file errors appear and nothing really works.

**Comment by eunovm** [comment]
Thank you for the report. I just updated the link to the build base for LInux 3.14.79. Indeed, it was incompatible with new versions of Klever. Also, you can find links to build bases for Linux 5.5 and Linux 5.10.27 in the updated tutorial.

 As for the issue with Clade, I will try to reproduce it.

**Comment by eunovm** [comment]
I could reproduce it. Here is the file causing the same issue for me: [init_global.txt](https://github.com/17451k/clade/files/8390794/init_global.txt). I see that Linux kernel developers changed these initializers in new versions of the Linux kernel, but earlier Clade handled them.

**Comment by eunovm** [comment]
@17451k revealed that this issue is caused by a bug in underlying tool. I opened a corresponding [bug](https://forge.ispras.ru/issues/11518). My suggestion is to do nothing in Clade, since implicit ignoring of encoding issues can result in missing something important one day.

**Comment by eunovm** [comment]
BTW, I fixed the appropriate [issue](https://forge.ispras.ru/issues/11518). After that I could successfully generate the build base for Linux 3.14.79. I will update CIF in Klever in a while.
