### ISSUE TITLE
Change the format of cmds.txt file

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#24]
At the moment, the commands arguments are separated by the "||" characters. These characters can also occur in the arguments themselves, so it would be better if we structure this file a little bit differently.

**Comment by 17451k** [comment]
New format should also support getting environment of intercepted commands.

**Comment by eunovm** [comment]
> New format should also support getting environment of intercepted commands.

I already recommended to save information on environment variables incrementally. For instance, you can save all environment variables for a main build command, and then you can save diff for all other build commands.
