### ISSUE TITLE
Each extention object always creates a tmp dir and does not clean it

### ISSUE THREAD

**Issue by IljaZakharov** [17451k/clade#29]
Class Extention constructor contains the following code:
`    def __init__(self, work_dir, conf=None, preset="base"):
        ...
        self.temp_dir = tempfile.mkdtemp()`

This leads to creation of billions of dirs in /tmp  even if  a user is not going to call parse method.

**Comment by 17451k** [comment]
Proposed solution (f686cfc79c0d57124551fde6317e4e897c6a2348) is good, so I am going to close the issue.

However, it is difficult to imagine how this bug can lead to the creation of  billions of directories inside the /tmp directory. I  suppose you will explain it to me later. Nevertheless, I apologise for the inconvenience.
