### ISSUE TITLE
Clade occupies memory during normalizing CIF output uselessly (likely)

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#32]
Log: "11:43:51 clade Info: Normalizing CIF output".
System monitor state:
![clade eats memory](https://user-images.githubusercontent.com/16303309/47490568-a9f29c80-d851-11e8-8735-190557675e9f.png)

**Comment by eunovm** [comment]
It seems that just 2 of 9 workers do some job.

**Comment by 17451k** [comment]
This tiny fix - 27643d50beee1298bda034e5d8bbd61e29242e61 - should mitigate the problem.
