### ISSUE TITLE
Failed building wheel for clade

### ISSUE THREAD

**Issue by mpodos** [17451k/clade#33]
pip3 install clade (Ubuntu):
Failed building wheel for clade
error: can't copy 'clade/libinterceptor/lib': doesn't exist or not a regular file
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0cttqg1y/clade/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1b0ttqqp/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0cttqg1y/clade/

**Comment by 17451k** [comment]
Unfortunately, I won't be able to look at this problem and fix it until next week.
As a workaround, you can try to install Clade directly from the repository.
