### ISSUE TITLE
Add ability to preprocess intercepted build commands before their execution 

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#39]
Without this it is impossible to properly work with commands that store their arguments in temporary files, like some Microsoft build utilities:

`cl.exe @"C:\Users\shchepetkov\AppData\Local\Temp\tmp0a392aa8bcbf41339a14bcbe325dd7d1.rsp"`

**Comment by eunovm** [comment]
Regarding placing command-line arguments in files, GCC also supports this. Please, read [this](https://stackoverflow.com/questions/7139685/does-gcc-support-command-files) and [this](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Overall-Options.html#Overall-Options). Corresponding files may be temporary as well.

This enhancement can be treated as more generic although it is not specified in the issue description. Indeed, in this way we can process all files that are removed after builds are completed. These files are not necessary temporary ones and they can be even source files.

Another bad case is overwriting required [likely just source] files during builds. Let's assume that for build command A a build process generates source file in.c and then it removes it and generates one more time but with different content for build command B. So, in ideal you need to store both versions of the same file and allow to rather easily and efficiently to use a required version of it. Although this is possible but it seems to happen much less often than just removing files during builds. Thus, we can keep this in mind but do not implement, as it is quite hard, it complicates usage and breaks performance.

**Comment by 17451k** [comment]
My implementation will be very generic: it will allow any extension to perform any action on intercepted build command (including its changing) before its execution. For example, if CC extension will want to save some file that will be overwritten, or to read command-line arguments from a temporary file - it will be able to do so.

And thank you for information about command files - it is quite interesting.

**Comment by 17451k** [comment]
Implemented, but currently not used.

**Comment by eunovm** [comment]
I suggest to support an ability to get dependencies for C files as well as to preprocess them in parallel with build (likely there should be an option that will change current implementations slightly rather than a completely different implementations). You can introduce a simple test case that will fail without this, e.g. some header files and even C files can be created and removed during a build.
