### ISSUE TITLE
CIF doesn't print information about exported functions for the Linux kernel

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#4]
Probably `info: expand(__EXPORT_SYMBOL(sym, sec)) `request doesn't work properly.

**Comment by eunovm** [comment]
There is a dedicated project for CIF: https://forge.ispras.ru/projects/cif.

**Comment by 17451k** [comment]
Fixed in 0e493b2e023084d52b091f449074fa57aa7b618e.
