### ISSUE TITLE
Build indexes for cross referencing

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#40]
Recently we discussed that cross referencing is a very valuable feature for users. Clade should perform additional code querying for gathering necessary data and generate indexes for source files.

**Comment by eunovm** [comment]
[Here](https://forge.ispras.ru/issues/9443) is the blocking issue.

**Comment by eunovm** [comment]
Indeed, this is quite important issue that will change vital data formats and API. So, I suggest to make it in 3.0.

**Comment by 17451k** [comment]
Until the blocking issue will not be implemented, all I can do is to postpone it over and over again.

**Comment by eunovm** [comment]
It seems that Clade already can build indexes that will be accurate enough. There are just several cases when it will obtain invalid data without additional information from CIF.

Among other features and bugs this is the most important for Klever and its users.

**Comment by 17451k** [comment]
There is now "CrossRef" extension that can obtain all necessary data.
