### ISSUE TITLE
Allow calculating check sums for stored sources

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#41]
To easily distinguish different stored sources using check sums calculated in advance seem to be the best solution. Other solutions like providing attributes for stored sources, calculating check sums on the fly or archiving sources and comparing archive sizes are worse by different reasons.

**Comment by eunovm** [comment]
According to code changes, I suggest that you calculate check sums for individual source files. Perhaps this is necessary in some use cases, but not in the one targeted by this issue. Unfortunately, the issue description was not precise enough. Users need a single check sum for all stored files for a given build base.

Instead of the completely proper solution to calculate check sums for directories (you may see recommendations [here](https://stackoverflow.com/questions/24937495/how-can-i-calculate-a-hash-for-a-filesystem-directory-using-python), you can calculate a check sum for check sums for all source files. Likely you can do the latter without creating intermediate files (in memory) and even on demand, that is just if one will request for a single check sum. Of course users can do this themselves but this scenario seems to be quite generic.

**Comment by 17451k** [comment]
I suggest to use the universally unique identifier (UUID) of the Clade working directory instead. You can get it using get_uuid() interface method starting from 346e3476839e4f0c9b1e79fb4ab63627ace58648.

Please close if it is sufficient for you.

**Comment by eunovm** [comment]
I think that your decision matches the original purpose much better, since it will help and it does not take considerable computational resources.
