### ISSUE TITLE
Do not blame CIF when it was not run

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#44]
If Clade does not run CIF at all (e.g. this is the case when there aren't input files), it still blames it that it fails on every command. Instead, I expect that there should be errors, e.g. that input files are missed.

**Comment by 17451k** [comment]
It is not possible to identify the correct cause of failure since CIF is executed in parallel, but at least Clade can shift blame from CIF to intercepted compilation commands. Implemented in master branch.
