### ISSUE TITLE
There may be no declarations in some files when processing function calls during building call graphs

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#46]
See details at: clade/extensions/callgraph.py:121-122.

BTW, this was mentioned at #45.

**Comment by 17451k** [comment]
Should be already fixed in Vadim's pull request (merged to master). Need confirmation.

**Comment by eunovm** [comment]
It still can fail.

**Comment by 17451k** [comment]
I made another attempt at fixing this in b31a9d4589524a14f21fde97ad07d7fba5e43e22.

**Comment by eunovm** [comment]
I do not see this issue anymore.
