### ISSUE TITLE
Evaluate and output progress

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#47]
I think that for some long operations of Clade, e.g. querying source code, you can evaluate and output a progress quite easily.

The issue is not very important since Clade does not work very much time first and it is not intended to be invoked often.

**Comment by 17451k** [comment]
That would be quite useful.

**Comment by 17451k** [comment]
Partially implemented. Will work further.

**Comment by eunovm** [comment]
I suggest to print percents in addition to raw numbers:
```
         6608 of 37168 commands are parsed
```

Percents will change slightly in comparison with raw numbers.

**Comment by 17451k** [comment]
Done.
