### ISSUE TITLE
Check for file "functions.json" existence

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#49]
When directory "Functions" exists Clade still needs to check for file "functions.json" existence.

**Comment by 17451k** [comment]
If Functions extension raises an exception, that the is no "Functions" directory. Otherwise, there is both - directory and "functions.json" file. Why they should be checked together?

**Comment by eunovm** [comment]
Maybe "functions.json" is not always created. For instance, if something underlying fails. So, next invocation of Clade will result in this issue, when other extensions will try to access a nonexistent file.

**Comment by 17451k** [comment]
#76 will address this issue better.
