### ISSUE TITLE
CIF still doesn't work on macOS

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#5]
The reason is Linux-specific command line tools used in cif.c file.

CIF is an optional dependency of Clade used for getting information about source code.

**Comment by eunovm** [comment]
There is a dedicated project for CIF: https://forge.ispras.ru/projects/cif.

**Comment by 17451k** [comment]
Implemented in 17451k/cif@34b4132a824161376180dbeeb6f6479179fe762e
