### ISSUE TITLE
PidGraph for Windows looks bad

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#52]
I suggest that it is not used in this state anywhere. Thus, it is better to disable it at all.

Another way is to fix it if this is possible/required.

**Comment by 17451k** [comment]
PidGraph for Windows is not supported, but it is also not really needed right now. To support it Clade will need to read/write environments of other processes through Windows debugging API.

**Comment by 17451k** [comment]
This feature requires new format of cmds.txt file (see issue #24).

**Comment by 17451k** [comment]
PidGraph for Windows is supported starting from a79a2721399e7c5a32d6deb58fe14ae42df086e0.

Example for the Curl project:
[curl_pid_graph.pdf](https://github.com/17451k/clade/files/3453049/curl_pid_graph.pdf)
