### ISSUE TITLE
Clade Link should additionally search for input files

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#53]
At the moment it can refer to nonexistent object files as input files although they exist but in other directories rather than CWD. Those directories are specified via command-line options.

**Comment by 17451k** [comment]
This will require knowledge of the intercepted command environment to determine where exactly these input files are located.

**Comment by eunovm** [comment]
Okay, but at least let's avoid to point out nonexistent object files if this is not so hard. For instance, for, say, _a.obj_ that isn't resided in a Link working directory Clade shouldn't assume that it is there.

**Comment by eunovm** [comment]
Link has option _/LIBPATH_ that can help to resolve some file paths. LD has option _-L_. Also, there are some extra options and many search paths are assumed by default. In general case, environment variables can affect this as well.

Eou can get all library search paths from LD and GCC: https://stackoverflow.com/questions/9922949/how-to-print-the-ldlinker-search-path. Perhaps this is also the case for Link. But after all it will likely be too hard to get actual input files. Thus, it may be better to analyze linker output files, to understand input files. On Linux there is tool _ldd_ for that. For Windows _dumpbin_ or something else can help.

**Comment by eunovm** [comment]
I don't think that low priority issues should be included in 3.0.

BTW, I suggest that this particular issue will take quite much time for implementation since you will need to change very many things related with linking. But the priority says that this is not very important for users.

**Comment by 17451k** [comment]
/libpath for Link is support in 3fc12f9a243bfc4c9525523df8e68fa8c87ef993.

**Comment by 17451k** [comment]
-l option for LD was supported in 96646ea8, so I consider this issue resolved.

**Comment by eunovm** [comment]
Confirm. Great work!
