### ISSUE TITLE
Clade evaluate common filters many times

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#54]
Since the corresponding class is a base class for several extensions and there is no caching, common filters are evaluated for all of them.

**Comment by 17451k** [comment]
Filters are stored in the configuration which is available only on as an instance variable. Due to this object initialisation method is the only possible location for such evaluation.

I suggest to run profiler on Clade to measure resources that are wasted on such repeated actions.

**Comment by eunovm** [comment]
I suggest that further work with this issue will wast more human resources than computation ones.
