### ISSUE TITLE
Clade provides invalid file paths when querying source code

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#55]
This results in, say, the following file paths are printed in _call.txt_ (I kept slashes, cases and basic layouts):
`C:\Path\to\Dir\/c:\path\to\dir\Filename`

**Comment by 17451k** [comment]
The issue should be fixed now, at least partially. Awaiting for feedback.

**Comment by eunovm** [comment]
It seems to be non fixed in several places.

**Comment by 17451k** [comment]
The fix we did today is wrong. We will need to debug the issue again tomorrow.
