### ISSUE TITLE
Take into account that CL can include headers ending with spaces

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#56]
Surprisingly, but this is normal to write such the include directive on Windows:
`#include "header.h "`
After all this result in issues with invalid CIF output because there are more than one space used as a delimiter.

This happens just when preprocessed sources are stored and used. Perhaps it is better to fix up line directives there rather than to overcome the issue somehow else.

**Comment by 17451k** [comment]
Should work now.

**Comment by 17451k** [comment]
It would be better to wait for feedback before closing the issue.

**Comment by eunovm** [comment]
Works for me.
