### ISSUE TITLE
Develop Clade API tests

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#67]
To avoid fixes of issues like #66 that are quite hard for identifying it would be much better to have basic tests for all Clade API.

**Comment by 17451k** [comment]
Such tests are here: [test_interface.py](https://github.com/17451k/clade/blob/master/tests/test_interface.py)

The problem is that they are too basic.

**Comment by eunovm** [comment]
Within this issue I suggest to invoke all functions of the API at least one time and compare their results if so with expected ones.

**Comment by eunovm** [comment]
In addition to testing API that will likely not cover an all build base it has sense to compare a new build base with the referenced one. With #78 it should be trivial.

**Comment by 17451k** [comment]
Implemented in ebcee3c3a8c96f8e3f26a2954969d4d36655bff2.

Possibility to compare build bases automatically will be considered separately.
