### ISSUE TITLE
Add optimization options to CIF white list

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#68]
At the moment processing of 2 CC commands from all CC commands of a Linux 3.14.79 build (architecture: x86_64, configuration: allmodconfig) fails because of initializers are not constant. There is not such the issue during a normal build because of optimization options, namely "-Os".

I thought that you can avoid the issue by avoiding querying initializers, but this will not help since GCC itself fails to parse this code.

**Comment by 17451k** [comment]
I believe that adding only sets of optimization options (`-O, -O1, -O2, -O3, -O0, -Os, -Ofast and -Og`) will not be enough. We also need all possible optimization flags (see [docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options)).

**Comment by eunovm** [comment]
> I believe that adding only sets of optimization options (`-O, -O1, -O2, -O3, -O0, -Os, -Ofast and -Og`) will not be enough. We also need all possible optimization flags (see [docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options)).

I think more about this. Perhaps there may be cases when builds fail without some specific optimizations (in the mentioned example Clade does not need the whole "-Os" but perhaps one or two optimizations), but most likely most of optimizations do not affect builds and you can safely turn them off. Also, there may be tricky cases, when, say, bugs exist just when specific optimizations enabled/disabled but like with the previous case just several options matter. 

Since different versions of compilers support different specific optimization options we will need to filter them out often when using the option black list. This is not the case for "-O*" options. Thus, it is a good tradeoff to add this filter to the option white list.

**Comment by 17451k** [comment]
Optimization options are added in f06ce36554c0078d7b66da0770a3b9ab46fce781. Let's see how it will affect launches.

**Comment by 17451k** [comment]
It seems that everything is ok, no sign of regressions and non-constant initializers.
