### ISSUE TITLE
Store compiler input file dependencies in UTF-8

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#69]
At the moment Clade already does some tricks to detect encoding for various data (there are some separate issues there). For instance, it detects encoding for preprocessed source files and stores them in UTF-8.

I suggest to store all data in UTF-8 to simplify different further operations with it. Perhaps this is not the case just for compiler input file dependencies now.

**Comment by 17451k** [comment]
Implemented in 22aa528e01ae0d27071ae18645a6b20f56c22648, but not turned on by default because converting requires additional time and there may be some issues.

Option "Storage.convert_to_utf8" is available to use.

**Comment by eunovm** [comment]
Please, add one more option to specify input source files encoding like in other places, where decoding is used.

**Comment by eunovm** [comment]
I moved the latter to #84.

**Comment by eunovm** [comment]
Unfortunately, all stored files have extra new lines for each line on Windows.

**Comment by 17451k** [comment]
Should be fixed in eac61dfe64245ab74448f2bcd01b3166629805e6.

**Comment by eunovm** [comment]
Really fixed.
