### ISSUE TITLE
Support forcible operations

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#73]
If there is already a directory, say, Callgraph, then Clade does not calculate it again. One should removed that directory in advance and run Clade after that. Like some Linux commands Clade can support "-f|--force" that will cause Clade to remove directories itself.

Unfortunately this will not help in some cases, e.g. when you want to recalculate a call graph as well as to re-query source code since several additional directories should be removed as well. Perhaps Clade can remove not only a directory corresponding to a target operation but also directories corresponding to its dependencies, but I don't know is this so simple as I would like to see.

**Comment by eunovm** [comment]
There is an issue. For instance, "-fc" for Callgraph removes all directories within directory "clade".

**Comment by 17451k** [comment]
Can't reproduce.

**Comment by eunovm** [comment]
Me too.
