### ISSUE TITLE
Remember directory where clade-intercept is invoked

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#75]
In most cases this directory corresponds to a source tree root. Clade users need to know this directory, e.g. to specify file paths relatively to it.

**Comment by eunovm** [comment]
In addition, we would appreciate a dedicated API to store and to retrieve specific data files. At the moment we have to use the storage one for that, but this is a workaround.

**Comment by 17451k** [comment]
472bf9805bcd97e3f6e9b37375e3f7cbb5466199 adds ability to get path to the directory where the build process was performed, as well as some other information. In my experience, this directory is often separated from the directory with the source code, so maybe it will not be that useful for you.

**Comment by eunovm** [comment]
And what about the second part of this issue:

> In addition, we would appreciate a dedicated API to store and to retrieve specific data files. At the moment we have to use the storage one for that, but this is a workaround.

In particular, at the moment we save the following additional data for Clade build bases:

- Project attributes that are specific and could not be obtained by Clade itself, e.g. build configurations and project versions.
- Additional build directories when a project is not resided within a single directory. Definitely Clade also does not aware about that since it can not distinguish project directories itself. 
- Auxiliary data.

For all mentioned data we use 3 different files, but it is possible to put everything into one file as well as to retrieve all its content at a time.

**Comment by eunovm** [comment]
I moved the second part to #83.
