### ISSUE TITLE
CIF output may be non utf8

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#80]
This causes exceptions in _subprocess.check_output_ and abnormally terminates Clade soon after that.

**Comment by eunovm** [comment]
I suggest to print CIF output to temporary files and use "errors=replace" or "errors=backslashreplace" (https://docs.python.org/3/library/io.html#io.TextIOWrapper) when opening it.

**Comment by eunovm** [comment]
There are some workarounds that help to overcome this issue in particular cases, but it still exists.

**Comment by 17451k** [comment]
I need an example in order to reproduce the issue and fix it.

**Comment by eunovm** [comment]
After converting files to utf8 I do not observe this issue anymore, but we can encounter it one day again.
