### ISSUE TITLE
Clade should not treat preprocessing build commands like compilation ones

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#85]
For instance, on Windows for such the build command `cl /EP /P file.c` Clade thinks that its output is _file.obj_ and performs all corresponding actions such as querying source code. The latter can fail in case when _file.c_ is not a valid C source file.

I did not investigate if this is the issue on Liniux.

**Comment by 17451k** [comment]
Such commands must be filtered if someone (like Info extension and CIF) wants to get only compilation commands. Not all CL or CC commands are compilation commands, some of them are linker or preprocessor commands. The filtering is already implemented in the CC extension.

BTW, what do you mean by "file.c may be not a valid C file"?

**Comment by eunovm** [comment]
I filtered such the commands, but indeed I do not think that I should do that. In contrast, Clade should take care about this as well as non-standard workflows, e.g. when one preprocesses sources, then compiles them and then links together using the same tool. In this particular case, it should not query source code at all or after the macro instrumentation stage.

You can preprocess any file valid from the preprocessor point of view. But compiler can fail on preprocessed source code later.

**Comment by 17451k** [comment]
Implemented in 8225cef03aa5d22ec1a3f89a10928f3c5245742f.
