### ISSUE TITLE
Cannot install Clade into any specific directory

### ISSUE THREAD

**Issue by IljaZakharov** [17451k/clade#9]
Installing Clade with a command
``sudo pip3 install -t ../install .``

I do not have bin directory with required scripts. Without sudo it does not work at all because pip prevents installation at all (Ubuntu bug as far as I know):
``
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
``

**Comment by 17451k** [comment]
The issue can easily be fixed by upgrading pip.
