### ISSUE TITLE
Check for permissions

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#90]
Assume, when accessing a collected build base a given user does not have an access for directory _clade_. Then Clade can start to get a pid graph after _os.path.exists_ fails (it silently returns False when a user has not an access to a directory).

**Comment by eunovm** [comment]
You fix requires write permissions to the directory while often users need just to read them. Perhaps, you can check for permissions differently depending on user needs.

**Comment by 17451k** [comment]
Now Clade checks write permissions only before writing to the disk (483e67a4d9f383d48fbb64234de4ab141bde3ffa).

**Comment by 17451k** [comment]
Let's assume that everything is OK now and close the issue.
