### ISSUE TITLE
Simplify workflow for users

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#91]
Currently typical Clade workflow consists of the following steps:
- Intercept build commands using clade-intercept tool;
- Process intercepted commands using one or several tools like clade-src-graph, clade-cc, clade-callgraph;
- Access processed information either through Clade interface (recommended way) or directly.

I see at least two issues here. Firstly, separating build commands intercepting from their processing is convenient primarily to Clade developers, and not so to Clade users. It would be better if users could collect all needed information through one single and simple command.

Secondly, sometimes users do not understand which tools they need to use on the second step. Again, their sheer number are primarily useful only for Clade developers. I suggest running clade-src-graph by default in all cases, and to add an additional option to enable source code quering using CIF (or Clang).

So, insted if executing two commands:

```
$ clade-intercept make -j8
$ clade-callgraph -c conf cmds.txt
```

Users will execute one:
```
$ clade -c conf --query make -j8
```

As a side effect, cmds.txt file will be stored inside Clade working directory, like issue #88 suggests to do. And since cmds.txt will become an internal entity, it would be easier to change its format (issue #24 and #52).

@eunovm, I would like to hear your thoughts on this topic.

**Comment by eunovm** [comment]
First of all I agree in general, that for production you should simplify Clade interfaces as much as possible. For development purposes you can leave everything as is.

I agree that one command is better than several ones. 

I do not understand why source code querying is so important. Indeed, it is just an internal mechanism to obtain information valuable for users. Nobody will use source code query results as is, but one will use call graphs and so on. And users have to specify somehow what information they need (very close to #93).

Note that #88 also suggested to store configuration files within Clade working directories, so that at later stages one will not have to specify it again and again.

**Comment by eunovm** [comment]
I suggest to include kinds of data to be collected within configuration. For instance, if one is going to verify Linux kernel with help of Klever, he/she should invoke Clade like:
```
$ clade -p klever_linux_kernel make -j8
```
while Klever developers should take care about an actual preset configuration.

At the same time, basic preset configurations, say, "linux_kernel", can include generation just of some common basis, e.g. source and call graphs.

In other cases corresponding tool developers will take care about configurations themselves.

**Comment by 17451k** [comment]
c317aab521202e304b6ba6ba7ed527dad656c874 introduces new command-line interface. Other existing interfaces (clade-intercept, clade-src-graph, clade-callgraph, clade-all, etc) will be removed shortly. Usage examples:


Intercept build commands:
`$ clade -i make`

Intercept build commands and append them to the existing cmds.txt file:
`$ clade -i -a  --cmds /work/cmds.txt make`

Intercept build commands and launch SrcGraph extension:
`$ clade make`

Intercept build commands and launch specified extension:
`$ clade -e ExtensionName make`

Use pre-generated cmds.txt file and launch specified extension:
`$ clade -e ExtensionName --cmds cmds.txt`

Replacement for clade-intercept + clade-all, for Klever users:
`$ clade -p klever_linux_kernel make`

or for other projects:
`$ clade -p klever make`

@eunovm, your feedback will be appreciated.

**Comment by eunovm** [comment]
I like it with minor notes.

**Comment by 17451k** [comment]
I have implemented some of your notes and closing the issue.
